# -*- coding: utf-8 -*-
"""Step 45 - two loose ends left by 42/43.

(A) The complementary subset. 42_* showed the post-test escalation magnitude
    vanishes on the genuinely imputation-free +-7 subset (free7). The mirror
    image -- does it CONCENTRATE in the tests that did require filling? -- is
    what makes the claim "generated by the imputation" rather than "lost to
    power". Also reports the pooled (patient-clustered) estimates on free7,
    since 42_* ran within-patient only.

(B) De-duplication sensitivity for the primary cluster table. The pipeline
    retained same-patient-same-day repeat urine records (677 excess records in
    the raw file, 246 within the step-3 sample; 43_*). A same-day repeat
    produces a BIT-IDENTICAL 57-day raw dose window for the same patient with
    the same result, so those rows can be identified inside aim2.mat without
    the test date: duplicate (pid, raw 57-day window, outcome) tuples. The
    primary P/N table is recomputed with the extras dropped.

Writes dedup_complement.json
"""
import os as _os
ROOT = _os.environ.get('MMT_DATA_ROOT', '')  # local folder holding raw data/, code/, analysis/
if not ROOT: raise SystemExit('Set MMT_DATA_ROOT before running; patient data is not distributed.')

import h5py, numpy as np, pandas as pd, json, warnings; warnings.filterwarnings('ignore')
from scipy.special import i0
from sklearn.cluster import KMeans
import statsmodels.api as sm
from statsmodels.stats.multitest import multipletests
from statsmodels.discrete.conditional_models import ConditionalLogit

OUT = _os.path.join(ROOT, r'analysis')
f = h5py.File(_os.path.join(ROOT, r'code\including_False_N_splitdata_testingvalidating\aim2.mat'), 'r')
cells = lambda n: [np.array(f[r]) for r in np.array(f[n]).ravel()]
m2 = lambda a: (a.T if a.shape[0] == 57 else a); v = lambda a: np.array(a).ravel()
coeff = np.array(f['coeff']); mu0 = v(f['mu'])
afn = cells('All_fill_norm'); pos_pd, pos_ds, neg_pd, neg_ds = m2(afn[0]), m2(afn[1]), m2(afn[2]), m2(afn[3])
raw = cells('All_raw_fix'); rpos, rneg = m2(raw[0]), m2(raw[2])
hdr = cells('All_fill_header'); pid = np.r_[v(hdr[0]).astype(int), v(hdr[2]).astype(int)]
xa, xb = cells('slope_burst_max_7da'), cells('slope_burst_max_7db')
sa, sb = cells('slope_burst_min_7da'), cells('slope_burst_min_7db')
f.close()
TP, TN = 3401, 6499; y = np.r_[np.ones(TP), np.zeros(TN)]
POST = np.r_[v(xa[0]), v(xa[2])]; PRE = np.r_[v(xb[0]), v(xb[2])]
R = np.vstack([rpos, rneg])
free7 = ~(R[:, 21:36] == -1).any(1)
res = {}

def disc(mask):
    d = pd.DataFrame(dict(y=y[mask], g=pid[mask])); ok = d.groupby('g').y.nunique() == 2
    return d.g.map(ok).values

def within(mask, x, nm):
    k = disc(mask); xx = x[mask][k]; z = (xx - xx.mean()) / xx.std()
    r = ConditionalLogit(y[mask][k], z[:, None], groups=pid[mask][k]).fit(disp=0)
    b, se = r.params[0], r.bse[0]
    d = dict(n=int(k.sum()), OR=float(np.exp(b)), lo=float(np.exp(b - 1.96 * se)),
             hi=float(np.exp(b + 1.96 * se)), p=float(r.pvalues[0]))
    print('    %-34s n=%5d OR/SD=%.3f CI %.2f-%.2f p=%.2e %s' %
          (nm, d['n'], d['OR'], d['lo'], d['hi'], d['p'], 'SIG' if d['p'] < .05 else 'ns'))
    return d

def pooled(mask, x, nm):
    xx = x[mask]; z = (xx - xx.mean()) / xx.std()
    r = sm.Logit(y[mask], sm.add_constant(z)).fit(disp=0, cov_type='cluster',
                                                  cov_kwds={'groups': pid[mask]})
    b, se = r.params[1], r.bse[1]
    d = dict(n=int(mask.sum()), OR=float(np.exp(b)), lo=float(np.exp(b - 1.96 * se)),
             hi=float(np.exp(b + 1.96 * se)), p=float(r.pvalues[1]))
    print('    %-34s n=%5d OR/SD=%.3f CI %.2f-%.2f p=%.2e %s' %
          (nm, d['n'], d['OR'], d['lo'], d['hi'], d['p'], 'SIG' if d['p'] < .05 else 'ns'))
    return d

print('=== (A) imputation-free vs imputation-REQUIRING +-7 windows ===')
print('  post-test escalation magnitude (mx_a):')
res['post_within_free7'] = within(free7, POST, 'within-patient | free7')
res['post_within_notfree7'] = within(~free7, POST, 'within-patient | NOT free7 (filled)')
res['post_pooled_free7'] = pooled(free7, POST, 'pooled          | free7')
res['post_pooled_notfree7'] = pooled(~free7, POST, 'pooled          | NOT free7 (filled)')
print('  pre-test escalation (mx_b):')
res['pre_within_free7'] = within(free7, PRE, 'within-patient | free7')
res['pre_within_notfree7'] = within(~free7, PRE, 'within-patient | NOT free7 (filled)')
res['pre_pooled_free7'] = pooled(free7, PRE, 'pooled          | free7')
print('  subset sizes: free7 n=%d (pos %d/neg %d); NOT free7 n=%d (pos %d/neg %d)'
      % (free7.sum(), int(y[free7].sum()), int((y[free7] == 0).sum()),
         (~free7).sum(), int(y[~free7].sum()), int((y[~free7] == 0).sum())))

# ---------------- (B) de-duplication ----------------
print('\n=== (B) same-patient-same-day repeat records inside the analysable sample ===')
key = [(int(pid[i]), int(y[i]), R[i].tobytes()) for i in range(len(y))]
s = pd.Series(range(len(key)))
df = pd.DataFrame(dict(k=key))
first = ~df.k.duplicated()
n_extra = int((~first).sum())
print('  rows with a bit-identical (patient, 57-day raw window, result) twin: %d extra rows'
      % n_extra)
print('     of which positive %d, negative %d'
      % (int(y[~first.values].sum()), int((y[~first.values] == 0).sum())))
print('  de-duplicated sample: %d tests (%d pos / %d neg)'
      % (int(first.sum()), int(y[first.values].sum()), int((y[first.values] == 0).sum())))
res['dedup'] = dict(n_extra=n_extra, n_extra_pos=int(y[~first.values].sum()),
                    n_extra_neg=int((y[~first.values] == 0).sum()),
                    n_dedup=int(first.sum()))

# rebuild the taxonomy (same method as 36/40/42)
up = ~(np.abs(np.diff(pos_pd[:, 21:36], axis=1)).sum(1) != 0); svp = ~up
un = ~(np.abs(np.diff(neg_pd[:, 21:36], axis=1)).sum(1) != 0); svn = ~un
proj = lambda A, B, mk: (np.hstack([A[mk], B[mk]]) - mu0) @ coeff.T
thp = np.arctan2(proj(pos_pd, pos_ds, up)[:, 1] - .0270, proj(pos_pd, pos_ds, up)[:, 0] + .04) % (2 * np.pi)
thn = np.arctan2(proj(neg_pd, neg_ds, un)[:, 1] - .0270, proj(neg_pd, neg_ds, un)[:, 0] + .04) % (2 * np.pi)
G = np.linspace(0, 2 * np.pi, 721)[:-1]
dd = np.array([np.exp(12 * np.cos(g - thp)).sum() for g in G])
cuts = np.sort(G[[i for i in range(len(dd)) if dd[i] < dd[(i - 1) % len(dd)] and dd[i] <= dd[(i + 1) % len(dd)]]])
def vmpdf(t, m, k): return np.exp(k * np.cos(t - m)) / (2 * np.pi * i0(k))
def vm_mle(t, w):
    C = (w * np.cos(t)).sum(); S = (w * np.sin(t)).sum(); s = w.sum() + 1e-12
    Rr = min(np.sqrt(C * C + S * S) / s, .999); return np.arctan2(S, C), Rr * (2 - Rr * Rr) / (1 - Rr * Rr)
t1 = np.arctan2(v(sb[0])[svp], v(sa[0])[svp]); t2 = np.arctan2(v(xb[0])[svp], v(xa[0])[svp])
lab0 = KMeans(6, n_init=5, random_state=0).fit_predict(np.column_stack([np.cos(t1), np.sin(t1), np.cos(t2), np.sin(t2)]))
P = np.zeros((6, len(t1))); P[lab0, np.arange(len(t1))] = 1
m1 = np.zeros(6); k1 = np.ones(6); mm = np.zeros(6); k2 = np.ones(6); pi = np.ones(6) / 6
for _ in range(120):
    for k in range(6): w = P[k]; m1[k], k1[k] = vm_mle(t1, w); mm[k], k2[k] = vm_mle(t2, w); pi[k] = w.mean() + 1e-9
    P = np.array([pi[k] * vmpdf(t1, m1[k], k1[k]) * vmpdf(t2, mm[k], k2[k]) for k in range(6)]); P /= P.sum(0) + 1e-300
asg = lambda a, b, c, d: np.array([pi[k] * vmpdf(np.arctan2(b, a), m1[k], k1[k]) * vmpdf(np.arctan2(d, c), mm[k], k2[k]) for k in range(6)]).argmax(0)
clab = np.empty(TP + TN, object)
clab[:TP][up] = [f'PCA-{c+1}' for c in np.searchsorted(cuts, thp) % len(cuts)]
clab[:TP][svp] = [f'7d-{c+1}' for c in P.argmax(0)]
clab[TP:][un] = [f'PCA-{c+1}' for c in np.searchsorted(cuts, thn) % len(cuts)]
clab[TP:][svn] = [f'7d-{c+1}' for c in asg(v(sa[2])[svn], v(sb[2])[svn], v(xa[2])[svn], v(xb[2])[svn])]

def table(mask, nm):
    tp = int(y[mask].sum()); tn = int((y[mask] == 0).sum())
    rows = []; ps = []
    for c in sorted(set(clab)):
        a = int((mask & (clab == c) & (y == 1)).sum()); b = int((mask & (clab == c) & (y == 0)).sum())
        if a < 5 or b < 5: continue
        inc = ((clab == c)[mask]).astype(float)
        r = sm.Logit(y[mask], sm.add_constant(inc)).fit(disp=0, cov_type='cluster', cov_kwds={'groups': pid[mask]})
        rows.append(dict(cluster=c, pos=a, neg=b, PN=(a / tp) / (b / tn), OR=float(np.exp(r.params[1]))))
        ps.append(float(r.pvalues[1]))
    q = multipletests(ps, method='fdr_bh')[1]
    for r_, qq in zip(rows, q): r_['q'] = float(qq)
    print(f'  --- {nm} (n={int(mask.sum())}) ---')
    for r_ in sorted(rows, key=lambda z: -z['PN']):
        print('    %-7s pos=%4d neg=%4d P/N=%.2f OR=%.2f q=%.2g' % (r_['cluster'], r_['pos'], r_['neg'], r_['PN'], r_['OR'], r_['q']))
    return rows

allm = np.ones(TP + TN, bool)
res['table_full'] = table(allm, 'primary (as published, duplicates retained)')
res['table_dedup'] = table(first.values, 'de-duplicated')
delta = {a['cluster']: round(b['PN'] - a['PN'], 4) for a, b in zip(res['table_full'], res['table_dedup']) if a['cluster'] == b['cluster']}
print('  P/N change on de-duplication:', delta)
res['pn_delta'] = delta
json.dump(res, open(OUT + r'\dedup_complement.json', 'w'), indent=2)
print('\nsaved dedup_complement.json')
