#!/usr/bin/env python3
"""backup_index.py -- prints the backup index from the filesystem, on demand.

WHY THIS REPLACES A STORED FILE.
paper/BACKUP_INDEX.md was a stored enumeration of every .bak_* file in the project. It went stale
repeatedly -- the FIRST time inside the round that created it, five seconds after it was written.
Each time it was regenerated by hand, and each time a later edit created another backup and the
stored counts became wrong again.

A derived fact stored as a file is a copied fact with no expiry date. That is this project's founding
defect class, and it was being committed in the artifact whose entire purpose is provenance. The
stored file's own regeneration rule -- "it must be regenerated, not hand-edited, whenever a backup is
added" -- is a standing instruction that depends on a human remembering, which is the control this
project has repeatedly shown does not hold.

So the index is no longer stored. It is computed. There is nothing to go stale.

WHAT IT PRINTS.
One row per .bak_* file: tag, target, byte count, mtime, and -- for numeric rNN tags -- whether the
backup is byte-identical to the live file it shadows. Byte-identity CORROBORATES the pre-image
convention -- it shows no edit has landed since -- but does not prove it, being equally consistent
with a post-image.

THE NAMING CONVENTION IT ASSUMES, stated because it is a project decision and not a fact about disk:
    .bak_rNN_<file>  holds the state of <file> immediately BEFORE edit N. A pre-image, never a
    post-image. rNN is a monotonically increasing EDIT-SEQUENCE COUNTER, not a council round number;
    the two interleave and no claim mapping one to the other is safe.
Word-tagged backups (.bak_round43_, .bak_padfix_, ...) carry no counter and cannot be ordered.

USAGE
    python backup_index.py              # the full index, markdown
    python backup_index.py --check      # exit 1 if any pre-image differs from its live counterpart
                                        # AND is newer than it. This is the only DETECTABLE
                                        # contradiction, not the only possible one: a post-image
                                        # taken just after edit N becomes older than live as soon as
                                        # edit N+1 lands, so the ordinary mislabel is invisible here.
Output goes to stdout. This script writes nothing.
"""

import argparse
import datetime
import hashlib
import io
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
TAG = re.compile(r"^\.bak_(r\d+|[A-Za-z][A-Za-z0-9]*)_(.+)$")

#: Documents whose CONTENTS are off-limits to cold reviewers. This index enumerates them --
#: name, size, mtime are what an index needs -- but never reads their bytes.
#:
#: WHY THIS EXISTS. A reviewer honouring the prohibition ran this script, and the script
#: hashed every .bak_* file it found, byte-reading the prohibited ones on the reviewer's
#: behalf. Nobody designed that; the prohibition was written as a rule about what a READER
#: OPENS, and a tool the reader invokes obeys no such rule.
#:
#: The test is applied to the TARGET filename, not to the backup name and not to the tag. A
#: backup whose TAG merely resembles a prohibited prefix shadows an ordinary file and must not
#: be suppressed; widening the pattern until it also matches tags is the over-broad-pattern
#: failure this project has logged repeatedly.
#:
#: Because the split between tag and target is ambiguous (see parse), the test is applied to
#: EVERY candidate target, not only the resolved one. Blocking is deliberately the conservative
#: side of the ambiguity: a wrongly enumerated row costs a row, a wrongly hashed one costs the
#: boundary.
PROHIBITED = re.compile(
    r"^(WATCHDOG\.md$|COUNCIL_|PREREG_|PREREGISTRATION_|HANDOFF|RESULTS_negative\.md$)",
    re.IGNORECASE)


def prohibited(target):
    """True if the file this backup shadows has contents no reviewer may open."""
    return bool(PROHIBITED.match(os.path.basename(target)))


# The .bak_<tag>_<target> convention cannot be parsed from the name alone: a tag may contain
# underscores, so ".bak_a_b_c.py" splits as (a, b_c.py) or (a_b, c.py) with equal syntactic
# warrant. The convention adopted here resolves it by ASKING THE FILESYSTEM which candidate
# target exists, and it is deliberately conservative in three ways:
#   * the strict split wins whenever its target exists, so no row that already resolved can
#     change meaning;
#   * an extended split is accepted only when exactly ONE candidate target exists;
#   * when several exist the row keeps the strict split and is NOT compared, because a wrong
#     comparison against a real file is worse than no comparison at all.
# The residual is stated rather than hidden: if the true target has been deleted and some other
# candidate happens to name a live file, the row will resolve to the wrong file. Resolution is
# reported per run in the output so that this is visible rather than assumed.
def splits(fn):
    """Every (tag, target) split of a .bak_ name, shortest tag first."""
    rest = fn[len(".bak_"):]
    out, i = [], -1
    while True:
        i = rest.find("_", i + 1)
        if i < 0:
            return out
        if rest[:i] and rest[i + 1:]:
            out.append((rest[:i], rest[i + 1:]))


def parse(dirpath, fn):
    """(tag, target, how) for a .bak_ name, resolving the ambiguity that the tag may contain _.

    Returns how in {"strict", "extended", "ambiguous", "fallback", "unparsed"}.
    """
    m = TAG.match(fn)
    cand = splits(fn)
    if not m and not cand:
        return "UNPARSED", fn, "unparsed"
    if m and os.path.isfile(os.path.join(dirpath, m.group(2))):
        return m.group(1), m.group(2), "strict"
    live = [(t, g) for t, g in cand if os.path.isfile(os.path.join(dirpath, g))]
    if len(live) == 1:
        return live[0][0], live[0][1], "extended"
    if m:
        return m.group(1), m.group(2), "ambiguous" if live else "fallback"
    return cand[0][0], cand[0][1], "ambiguous" if live else "fallback"


def sha(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 16), b""):
            h.update(chunk)
    return h.hexdigest()


def collect():
    rows = []
    for dirpath, _dirnames, filenames in os.walk(ROOT):
        for fn in filenames:
            if not fn.startswith(".bak_"):
                continue
            full = os.path.join(dirpath, fn)
            tag, target, how = parse(dirpath, fn)
            live = os.path.join(dirpath, target)
            blocked = any(prohibited(g) for _t, g in splits(fn)) or prohibited(target)
            identical = None
            if os.path.isfile(live) and not blocked:
                try:
                    identical = sha(full) == sha(live)
                except OSError:
                    identical = None
            rows.append({
                "tag": tag,
                "target": target,
                "rel": os.path.relpath(full, ROOT).replace("\\", "/"),
                "live_rel": os.path.relpath(live, ROOT).replace("\\", "/")
                            if os.path.isfile(live) else None,
                "bytes": os.path.getsize(full),
                "mtime": datetime.datetime.fromtimestamp(os.path.getmtime(full)),
                "live_mtime": datetime.datetime.fromtimestamp(os.path.getmtime(live))
                              if os.path.isfile(live) else None,
                "identical": identical,
                "blocked": blocked,
                "how": how,
                "numeric": bool(re.match(r"^r\d+$", tag)),
            })
    rows.sort(key=lambda r: (r["mtime"], r["rel"]))
    return rows


def emit(rows):
    w = sys.stdout
    num = [r for r in rows if r["numeric"]]
    word = [r for r in rows if not r["numeric"]]
    multi = sorted({r["tag"] for r in num
                    if sum(1 for x in num if x["tag"] == r["tag"]) > 1},
                   key=lambda t: int(t[1:]))
    w.write("# Backup index -- GENERATED, not stored\n\n")
    w.write("Printed by `scone/backup_index.py` at %s.\n"
            % datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
    w.write("**Do not save this output to a file.** It was stored, went stale repeatedly, and is "
            "computed for that reason.\n\n")
    w.write("**%d files: %d numeric `rNN` tags, %d word tags.**\n\n" % (len(rows), len(num), len(word)))
    w.write("`.bak_rNN_<file>` is a PRE-IMAGE: the state of `<file>` immediately before edit N. "
            "`rNN` is an edit counter, not a council round number.\n\n")

    for title, subset in (("Numeric `rNN` tags", num), ("Word tags", word)):
        w.write("## %s -- %d files\n\n" % (title, len(subset)))
        w.write("| tag | target | bytes | mtime | vs live |\n|---|---|---|---|---|\n")
        for r in subset:
            if r["blocked"]:
                vs = "*content not read (prohibited)*"
            elif r["identical"] is None:
                vs = "*(no live counterpart)*"
            elif r["identical"]:
                vs = "identical -- no edit since; consistent with a pre-image, not proof of one"
            else:
                vs = "differs"
            w.write("| `%s` | `%s` | %s | %s | %s |\n"
                    % (r["tag"], r["rel"].replace(".bak_%s_" % r["tag"], ""),
                       format(r["bytes"], ","), r["mtime"].strftime("%Y-%m-%d %H:%M:%S"), vs))
        w.write("\n")

    w.write("## What this does not establish\n\n")
    ident = sum(1 for r in rows if r["identical"] is True)
    w.write("- **Pre-image semantics are a CONVENTION, not an observation.** Byte-identity with the "
            "live file shows only that no edit has landed since, which is equally consistent with a "
            "post-image, so it corroborates the convention rather than proving it. "
            "Rows currently byte-identical: **%d of %d**.\n" % (ident, len(rows)))
    w.write("- **A tag is not unique.** %d numeric tags cover more than one file (%s), so "
            "`.bak_rNN_` identifies a file only together with the target name.\n"
            % (len(multi), ", ".join("`%s`" % t for t in multi) if multi else "none"))
    w.write("- **Not every `.bak_*` is a manuscript state.** The set includes scripts, build "
            "artifacts and hash sidecars.\n")
    w.write("- **Gaps are invisible here.** A file with no pre-image for a given edit simply has no "
            "row; absence of a row is not evidence an edit did not happen.\n")
    ext = [r for r in rows if r["how"] == "extended"]
    amb = [r for r in rows if r["how"] == "ambiguous"]
    w.write("- **The tag/target split is ambiguous when a tag contains `_`, and is resolved by "
            "asking the filesystem which candidate target EXISTS.** Rows resolved that way: **%d**"
            "%s. Rows where more than one candidate exists, left on the strict split and NOT "
            "compared: **%d**%s.\n"
            % (len(ext), "" if not ext else " (" + ", ".join("`%s`" % r["rel"] for r in ext) + ")",
               len(amb), "" if not amb else " (" + ", ".join("`%s`" % r["rel"] for r in amb) + ")"))
    w.write("\n" + read_report(rows))


TOLERANCE_S = 2.0   # cp and its source can land in either order within one operation


def read_report(rows):
    """What this run touched -- printed in the OUTPUT, not only claimed in the docstring.

    A docstring is a claim; output is a record. The finding that produced this function is
    that documentation did not stop a boundary breach, so the statement belongs where it is
    emitted every run and cannot drift from what the code does.
    """
    blocked = [r for r in rows if r["blocked"]]
    hashed = [r for r in rows if r["identical"] is not None]
    out = ["## What this run read\n",
           "**Enumerated (name, size, mtime only): %d files.** Every `.bak_*` under the "
           "project root.\n" % len(rows),
           "**Contents read (sha256 over the bytes): %d backups and their live "
           "counterparts.**\n" % len(hashed),
           "**Contents NOT read, prohibited: %d.** Enumerated by name, size and mtime; "
           "never opened:\n" % len(blocked)]
    for r in blocked:
        out.append("  - `%s`\n" % r["rel"])
    if not blocked:
        out.append("  *(none matched)*\n")
    return "".join(out)


def check(rows):
    """A pre-image that DIFFERS from its live file and is meaningfully NEWER than it contradicts
    the pre-image convention.

    Two exclusions, both stated rather than silent:
      * build artifacts (__pycache__, .pyc) -- a compiled file is regenerated by any import and its
        mtime carries no information about when a backup was taken;
      * differences under TOLERANCE_S -- a copy and its source routinely land in either order
        within the same operation. The constant is 2 s rather than sub-second because a copy of a
        large file can straddle a second boundary; the rationale and the constant are stated
        together because an earlier version justified 2 s by appealing to sub-second noise.
    """
    considered, bad, skipped = 0, [], []
    for r in rows:
        if r["identical"] is not True and r["live_mtime"] is None:
            continue
        if r["blocked"]:
            continue
        if "__pycache__" in r["rel"] or r["rel"].endswith(".pyc"):
            skipped.append(r)
            continue
        if r["identical"] is None:
            continue
        considered += 1
        if r["identical"] is False:
            delta = (r["mtime"] - r["live_mtime"]).total_seconds()
            if delta > TOLERANCE_S:
                bad.append((r, delta))
    print("checked %d backups with a live counterpart (%d build artifacts excluded, tolerance %.0fs)"
          % (considered, len(skipped), TOLERANCE_S))
    blocked = [r for r in rows if r["blocked"]]
    print("contents NOT read, prohibited: %d (enumerated by name/size/mtime only)" % len(blocked))
    for r in blocked:
        print("    %s" % r["rel"])
    for r in skipped:
        print("    excluded (build artifact): %s" % r["rel"])
    if not bad:
        print("no backup is meaningfully newer than its live file while differing from it.")
        return 0
    print("*** %d backup(s) contradict the pre-image convention ***" % len(bad))
    for r, delta in bad:
        print("    %s  backup is %.1fs newer than live and differs" % (r["rel"], delta))
    return 1


def main():
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true")
    a = ap.parse_args()
    rows = collect()
    if a.check:
        return check(rows)
    emit(rows)
    return 0


if __name__ == "__main__":
    sys.exit(main())
