"""Every number the manuscript may quote, with its source and its direction, in one file.

The manuscript is being rewritten because patch-editing it stopped converging. Eleven audit
rounds each fixed a local defect and broke a global consistency: the elbow sign was inverted BY
a patch, "five families" survived in the supplement after section 2.5 became eight, one weighting
arm acquired four different names, and a quoted bound (q <= 0.032) was the minimum of a set rather
than its maximum. Those are not arithmetic errors. Every one is a sentence disagreeing with
another sentence, which is what patching produces and what a single pass does not.

A rewrite from memory would reproduce them. This extracts the facts from the artefacts first, so
the prose can be written against a table with a source on every row rather than against the old
prose. Anything not in this file may not be asserted in the manuscript.

Each row carries:
    value       as it should be printed
    direction   what the sign MEANS in words, resolved here once, so the prose never has to
    source      artefact file and line
    family      which declared multiplicity family it belongs to, or "-" if none

Output: D:/ROWV_paper/FACTSHEET.md
"""
import glob
import io
import os
import re

RES = "D:/BioCV"
OUT = "D:/ROWV_paper/FACTSHEET.md"

# Artefacts that are current. A retired file must never reach the prose: BIOCV_EQUIV.txt and
# BIOCV_ROUND5.txt each mixed live results with an abandoned-denominator table, and while they
# counted as current their superseded values sat in the pool the drift check compares against.
SKIP = ("_SUPERSEDED_",)

FAMILY_OF = {
    "BIOCV_PERM_V3.txt": "main (m = 50)",
    "BIOCV_INTERACTION_FDR.txt": "position vs angle (m = 20)",
    "BIOCV_JOINTSET_FDR.txt": "joint set vs joint set (m = 8)",
    "BIOCV_PERJOINT_FDR.txt": "per-joint (m = 12)",
    "BIOCV_POSTURE_FDR.txt": "posture (m = 13)",
    "BIOCV_SUBSET_CONTROL.txt": "within-limb (m = 30 / 30 / 20)",
    "BIOCV_POOLED_SENSITIVITY.txt": "pooled union (m = 183)",
}

# A verdict line in any of the family artefacts: label ... p q verdict [optional flag]
# The trailing flag is not decoration. The posture family carries a row marked [circular] --
# a test whose outcome is guaranteed by how the bins were formed -- and an earlier version of
# this pattern anchored on end-of-line, silently dropping exactly that row and reporting 182
# contrasts where the families sum to 183. A fact sheet that quietly loses the one row nobody
# may quote is worse than no fact sheet.
VERDICT = re.compile(r"^(.*?)\s{2,}([+-]?\d+\.\d+)\s+(\d\.\d{3,4})\s+(\d\.\d{3,4})\s+"
                     r"(SURVIVES(?: FDR)?|raw only|n\.s\.)\s*(\[[^\]]+\])?\s*$")


def rows():
    out = []
    for path in sorted(glob.glob(os.path.join(RES, "BIOCV_*.txt"))):
        base = os.path.basename(path)
        if any(s in base for s in SKIP):
            continue
        for n, line in enumerate(io.open(path, encoding="utf-8", errors="replace"), 1):
            m = VERDICT.match(line.rstrip())
            if not m:
                continue
            label, eff, p, q, verdict, flag = m.groups()
            out.append({
                "label": " ".join(label.split()),
                "effect": eff, "p": p, "q": q, "verdict": verdict + (" " + flag if flag else ""),
                "src": f"{base}:{n}",
                "family": FAMILY_OF.get(base, "-"),
            })
    return out


# The direction rule, stated once. Every family artefact defines a POSITIVE effect as "the
# second-named arm has the lower error", i.e. positive = the treated arm is BETTER -- except the
# angle rows of the m=50 family, whose labels name the treated arm first. Rather than encode that
# exception and risk getting it wrong the way the elbow row was, each artefact's own stated rule
# is quoted here and the prose must read it.
def direction_notes():
    notes = []
    for path in sorted(glob.glob(os.path.join(RES, "BIOCV_*.txt"))):
        base = os.path.basename(path)
        if any(s in base for s in SKIP):
            continue
        txt = io.open(path, encoding="utf-8", errors="replace").read()
        for m in re.finditer(r"^.*POSITIVE.*$", txt, re.M):
            notes.append((base, m.group(0).strip()))
        for m in re.finditer(r"^.*positive\s*=.*$", txt, re.M):
            notes.append((base, m.group(0).strip()))
    seen, uniq = set(), []
    for b, s in notes:
        if (b, s) not in seen:
            seen.add((b, s))
            uniq.append((b, s))
    return uniq


R = rows()
L = ["# Fact sheet — every quotable number, with its source and its direction", "",
     "Generated by `build_factsheet.py`. The manuscript may assert nothing that is not here.",
     "Retired `_SUPERSEDED_` artefacts are excluded.", "",
     "## Direction conventions, as each artefact states them", ""]
for b, s in direction_notes():
    L.append(f"- `{b}` — {s}")
L += ["", "## Contrasts", "",
      "| label | effect | p | q | verdict | family | source |", "|---|---|---|---|---|---|---|"]
for r in sorted(R, key=lambda r: (r["family"], float(r["q"]))):
    L.append(f"| {r['label']} | {r['effect']} | {r['p']} | {r['q']} | {r['verdict']} | "
             f"{r['family']} | `{r['src']}` |")

L += ["", f"{len(R)} contrasts across {len({r['family'] for r in R})} sources.", ""]
io.open(OUT, "w", encoding="utf-8").write("\n".join(L) + "\n")
EXPECT = {"main (m = 50)": 50, "position vs angle (m = 20)": 20,
          "joint set vs joint set (m = 8)": 8, "per-joint (m = 12)": 12,
          "posture (m = 13)": 13, "within-limb (m = 30 / 30 / 20)": 80}
got = {f: sum(1 for r in R if r["family"] == f) for f in EXPECT}
bad = {f: (EXPECT[f], got[f]) for f in EXPECT if EXPECT[f] != got[f]}
if bad:
    raise SystemExit("fact sheet incomplete, family sizes do not match section 2.5: "
                     + ", ".join(f"{f} expected {a} got {b}" for f, (a, b) in bad.items()))
print(f"wrote {OUT}: {len(R)} contrasts (families sum to {sum(got.values())})")
for fam in sorted({r["family"] for r in R}):
    print(f"  {fam:<34}{sum(1 for r in R if r['family'] == fam)}")
